(function(){'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);
function g(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ea={a:!0},p={};try{p.__proto__=ea;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var r=this||self;function t(a,b){a=a.split(".");var c=r;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};function fa(a){a=u(a,"autoplay-duration");return 0<a?a:29}function u(a,b){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=29);return a};var v,w;a:{for(var x=["CLOSURE_FLAGS"],y=r,z=0;z<x.length;z++)if(y=y[x[z]],null==y){w=null;break a}w=y}var A=w&&w[610401301];v=null!=A?A:!1;var B,C=r.navigator;B=C?C.userAgentData||null:null;function E(a){return v?B?B.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function F(a){var b;a:{if(b=r.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function G(){return v?!!B&&0<B.brands.length:!1}function H(){return G()?E("Chromium"):(F("Chrome")||F("CriOS"))&&!(G()?0:F("Edge"))||F("Silk")};!F("Android")||H();H();F("Safari")&&(H()||(G()?0:F("Coast"))||(G()?0:F("Opera"))||(G()?0:F("Edge"))||(G()?E("Microsoft Edge"):F("Edg/"))||G()&&E("Opera"));Object.freeze({});function I(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};function J(a,b){var c=void 0===c?r:c;c=c.performance;a={label:a,type:9,value:c&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):Date.now()};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var K={},L=!1,M=!1;K.N=function(a){L||(L=!0,J("11",a))};K.O=function(a){M||(M=!0,J("12",a))};K.J=function(a,b,c){var d=b;d=void 0===d?r:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===c?0:c,value:d},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};K.reset=function(a){M=L=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};t("gwd.rumUtil",K);t("gwd.rumUtil.logContentLoading",K.N);
t("gwd.rumUtil.logContentRendered",K.O);t("gwd.rumUtil.logTimingEvent",K.J);t("gwd.rumUtil.reset",K.reset);function ha(a){(0,K.J)("gwd3dmodelviewer_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);window.Enabler&&(a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame"))}function ia(a){window.Enabler&&(a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement"),N())}var O=0,ja=0;function N(){var a=Math.floor(performance.now()/100);0==O&&(O=a);for(a-=O;ja<=a;ja++)Enabler.counter("TotalSessionDurationDeciseconds",!0)}
var P={Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}};function Q(a,b){return window.setTimeout(a,b)};function R(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)};var ma=I({R:"animation-name",ba:"auto-rotate",W:"autoplay",aa:"autoplay-duration",ca:"camera-orbit",da:"camera-target",ea:"environment-image",fa:"exposure",ga:"field-of-view",la:"max-camera-orbit",ma:"max-field-of-view",na:"min-camera-orbit",oa:"min-field-of-view",pa:"poster",qa:"reveal",ra:"shadow-intensity",sa:"shadow-softness",ta:"skybox-image",ua:"src"}).concat(I({S:"ar",T:"ar-modes",U:"ar-placement",V:"ar-scale",ka:"ios-src"})),na=ma.concat(I({ha:"gesture-cue-duration",ia:"gesture-cue-icon",
ja:"gesture-cue-text"})),S=180/Math.PI;function T(){var a=HTMLElement.call(this)||this;a.i=null;a.v=!1;a.G=!1;a.B=null;a.F=null;a.l="hotspot-"+(2147483648*Math.random()|0);a.j=!1;a.D=a.M.bind(a);a.H=!1;return a}var U=HTMLElement;T.prototype=da(U.prototype);T.prototype.constructor=T;if(q)q(T,U);else for(var V in U)if("prototype"!=V)if(Object.defineProperties){var oa=Object.getOwnPropertyDescriptor(U,V);oa&&Object.defineProperty(T,V,oa)}else T[V]=U[V];f=T.prototype;
f.connectedCallback=function(){window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));pa(this)};f.disconnectedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.m&&(clearTimeout(this.m),this.m=void 0)};
f.attributeChangedCallback=function(){pa(this)};
f.handleEvent=function(a){var b=this,c=a.type,d=a.detail;switch(c){case "click":this.u&&a.target===this.h?a.stopPropagation():a.target&&qa(a.target)?(a.stopPropagation(),ra(this,a.target)):W(this);break;case "camera-change":"user-interaction"===d.source&&(this.i&&this.i.parentNode&&this.i.parentNode.removeChild(this.i),W(this),sa(this));a.stopPropagation();R("camera-changed",this,d);break;case "preload":case "load":this.classList.add("ready");ta(this);break;case "model-visibility":if(!d.visible)return;
this.G&&(ha(!1),this.G=!1,this.j=!0,ua(this),R("scene-rendered",this,null),X(this).dismissPoster());break;case "poster-dismissed":requestAnimationFrame(function(){R("poster-dismissed",b,null)})}window.Enabler&&(c===studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH?(X(this).setAttribute("touch-action","none"),Enabler.reportEngagement(),N()):c===studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH&&(X(this).setAttribute("touch-action","pan-y"),N()))};
function X(a){a.h||(a.h=a.ownerDocument.createElement("model-viewer"),a.h.setAttribute("camera-controls",""),a.h.setAttribute("interaction-prompt","none"),a.h.setAttribute("loading","eager"),a.h.setAttribute("data-js-focus-visible",""),a.h.setAttribute("touch-action","pan-y"),a.h.addEventListener("click",a),a.h.addEventListener("model-visibility",a),a.h.addEventListener("preload",a),a.h.addEventListener("load",a),a.h.addEventListener("camera-change",a),a.h.addEventListener("poster-dismissed",a),a.appendChild(a.h));
return a.h}function ua(a){if(a.hasAttribute("autoplay")){var b=X(a);b.pause();b.play();a=1E3*fa(a);0<=a&&Q(function(){b.pause()},a)}}function pa(a){a.m||(a.m=Q(a.gwdLoad.bind(a),1))}
f.gwdLoad=function(){var a=this;this.m&&(clearTimeout(this.m),this.m=void 0);customElements.whenDefined("model-viewer").then(function(){var b=a.h?a.h.getAttribute("src"):null,c=va(a,"src",!0);if(c){c!==b&&(a.v=!1,a.classList.remove("ready"),a.G=!0,a.j=!1,ha(!0));b=g(ma);for(c=b.next();!c.done;c=b.next())c=c.value,"src"!==c&&va(a,c);a.h&&a.h.jumpCameraToGoal();a.syncHotspotsToViewer();a.i&&a.i.parentNode&&a.i.parentNode.removeChild(a.i);if(c=a.getAttribute("gesture-cue-icon")){a.i=a.ownerDocument.createElement("div");
a.i.classList.add("gesture-cue-container");b=a.ownerDocument.createElement("div");b.classList.add("gesture-cue-icon");b.style.backgroundImage='url("'+c+'")';c=u(a,"gesture-cue-duration");b.style.animationIterationCount=0>c?"infinite, 1":(c/2).toFixed(1)+", 1";a.i.appendChild(b);if(b=a.getAttribute("gesture-cue-text"))c=a.ownerDocument.createElement("p"),c.classList.add("gesture-cue-text"),c.textContent=b,a.i.appendChild(c);a.appendChild(a.i)}}else ta(a)})};f.gwdIsLoaded=function(){return this.v};
function va(a,b,c){c=void 0===c?!1:c;var d=a.getAttribute(b);null==d||c&&!d?a.h&&a.h.removeAttribute(b):X(a).setAttribute(b,d);return a.h?a.h.getAttribute(b):null}function ta(a){a.v||(a.v=!0,R("ready",a))}function wa(a){a.u&&(300<Date.now()-a.L?Y(a,!1):requestAnimationFrame(function(){wa(a)}))}function sa(a){a.L=Date.now();window.Enabler&&Enabler.reportEngagement();a.u||Y(a,!0);requestAnimationFrame(function(){wa(a)})}
function Y(a,b){b?(a.u=!0,document.addEventListener("mouseup",a.D),document.addEventListener("touchend",a.D),P.Rotate&&P.Rotate(),ia(!0),R("interaction-start",a)):(a.u=!1,ia(!1),R("interaction-end",a))}f.M=function(){this.u&&(Y(this,!1),document.removeEventListener("mouseup",this.D),document.removeEventListener("touchend",this.D))};
function ra(a,b){W(a);var c=X(a).getElementsByClassName("hotspot");for(var d=-1,e=0;e<c.length;e++)if(c[e]===b){d=e;var h=a;if(b.ownerDocument&&b.ownerDocument.body){var l=b.getElementsByClassName("hotspot-annotation");if(0!==l.length){l=l[0];l.style.transform="";h=h.getBoundingClientRect();var k=l.getBoundingClientRect(),D=k.right;k=k.bottom;var ka=0,la=0;D>h.right&&(ka=Math.round(h.right-D)-5);k>h.bottom&&(la=Math.round(h.bottom-k)-5);l.style.transform="translate3d("+ka+"px, "+la+"px, 0px)"}}b.classList.add("selected");
a.B=b}c=d;if(-1!==c){d=b.getBoundingClientRect();e=b.querySelector("h3");b=b.querySelector("p");b={name:"Hotspot"+c,index:c,screenX:Math.round(d.left+d.width/2),screenY:Math.round(d.top+d.height/2),title:e?e.textContent:"",description:b?b.textContent:""};if(window.Enabler&&(Enabler.reportEngagement(),c="Hotspot"+(c+1)+"Click",P[c]))P[c]();R("hotspot-clicked",a,b)}}function Z(a){a.C||(a.C=Q(a.P.bind(a),1))}
f.P=function(){this.C&&(clearTimeout(this.C),this.C=void 0);var a=X(this).getCameraOrbit(),b=a.theta+"rad",c=a.phi+"rad";a=a.radius+"m";void 0!==this.A&&(b=this.A+"deg",this.A=void 0);void 0!==this.o&&(c=this.o+"deg",this.o=void 0);void 0!==this.s&&(a=this.s+"m",this.s=void 0);var d=X(this);d.cameraOrbit=b+" "+c+" "+a;this.H&&(this.H=!1,d.jumpCameraToGoal())};f.setYaw=function(a){this.j&&(this.A=a,this.H=!0,Z(this))};f.setTargetYaw=function(a){this.j&&(this.A=a,Z(this))};
f.setTargetPitch=function(a){this.j&&(this.o=a,Z(this))};f.incrementTargetPitch=function(a){this.j&&(this.o=void 0!==this.o?this.o+a:X(this).getCameraOrbit().phi*S+a,Z(this))};f.setTargetZoom=function(a){this.j&&(this.s=a,Z(this))};f.incrementTargetZoom=function(a){this.j&&(this.s=void 0!==this.s?this.s+a:X(this).getCameraOrbit().radius+a,Z(this))};f.setTargetPivot=function(a,b,c){this.j&&(X(this).cameraTarget=a+"m "+b+"m "+c+"m")};
f.setTargetLocalPan=function(a,b){if(this.j){var c=X(this),d=c.getCameraTarget().z;c.cameraTarget=a+"m "+b+"m "+d+"m"}};f.setMaterialColor=function(a,b,c,d){b=[b,c,d,1];c=X(this);c=g(c.model.materials);for(d=c.next();!d.done;d=c.next())if(d=d.value,d.name===a){d.pbrMetallicRoughness.setBaseColorFactor(b);break}};f.setMaterialClearCoat=function(){};f.playAnimation=function(a){var b=X(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.play()};
f.pauseAnimation=function(a){var b=X(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.pause()};f.setAnimationTime=function(a,b){var c=X(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.currentTime=b};f.incrementAnimationTime=function(a,b){var c=X(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.currentTime+=b};f.addHotspot=function(a,b,c,d){var e=X(this);a=xa({K:e,hotspotName:a,position:b+"m "+c+"m "+d+"m",normal:"",title:"",description:"",I:!0});e.appendChild(a)};
f.setHotspotInfoCard=function(a,b,c){var d=X(this);if(a=d.querySelector('div[slot="hotspot-'+a+'"]')){var e=a.getElementsByClassName("hotspot-annotation"),h=d.ownerDocument;0===e.length?(d=h.createElement("div"),d.classList.add("hotspot-annotation"),a.appendChild(d)):d=e[0];for(;d.firstChild;)d.removeChild(d.firstChild);a=h.createElement("h3");a.textContent=b;d.appendChild(a);b=h.createElement("p");b.textContent=c;d.appendChild(b)}};f.lookAtHotspot=function(){};f.lookAtHotspotIndex=function(){};
function W(a){a.B&&(a.B.classList.remove("selected"),a.B=null)}
function xa(a){var b=a.position,c=a.normal,d=a.title,e=a.description,h=a.I,l=a.K.ownerDocument,k=l.createElement("div");k.setAttribute("slot","hotspot-"+a.hotspotName);k.classList.add("hotspot");h&&k.setAttribute("info-card-hidden","");k.setAttribute("data-position",b);c&&k.setAttribute("data-normal",c);if(d||e)a=l.createElement("div"),a.classList.add("hotspot-annotation"),b=l.createElement("h3"),b.textContent=d,a.appendChild(b),d=l.createElement("p"),d.textContent=e,a.appendChild(d),k.appendChild(a);
return k}
f.syncHotspotsToViewer=function(){var a=X(this);if(a){for(var b=g(a.querySelectorAll(".hotspot")),c=b.next();!c.done;c=b.next())c=c.value,c.parentNode&&c.parentNode.removeChild(c);if(b=this.querySelector("gwd-3d-hotspot-container")){this.F&&(c=this.F,(c=c.ownerNode||c.owningElement||c)&&c.parentNode&&c.parentNode.removeChild(c),this.F=null,X(this).classList.remove(this.l));var d=b.getAttribute("up-image"),e=b.getAttribute("over-image"),h=b.getAttribute("down-image");c="";d&&(c+="model-viewer."+this.l+
' .hotspot { background: url("'+d+'") center / contain no-repeat; }');e&&(c+="model-viewer."+this.l+' .hotspot:hover { background: url("'+e+'") center / contain no-repeat; }');h&&(c+="model-viewer."+this.l+" .hotspot:active, model-viewer."+(this.l+' .hotspot.selected { background: url("')+h+'") center / contain no-repeat; }');d=b.getAttribute("width");e=b.getAttribute("height");if(d||e)c+="model-viewer."+this.l+" .hotspot {",d&&(c+="width: "+parseFloat(d)+"px; "),e&&(c+="height: "+parseFloat(e)+"px; "),
c+="}";d=b.getAttribute("background-color");e=b.getAttribute("font-color");h=b.getAttribute("border-color");if(d||e||h)c+="model-viewer."+this.l+" .hotspot-annotation {",d&&(c+="background-color: "+d+"; "),e&&(c+="color: "+e+"; "),h&&(c+="border-color: "+h+"; "),c+="}";c&&(X(this).classList.add(this.l),e=document,d=e.getElementsByTagName("head")[0],d||(h=e.getElementsByTagName("body")[0],d=e.createElement("head"),h.parentNode.insertBefore(d,h)),e=e.createElement("style"),e.textContent=c,d.appendChild(e),
this.F=e);c=0;b=g(b.children);for(d=b.next();!d.done;d=b.next())if(d=d.value,e=d.getAttribute("data-position")){h=d.getAttribute("data-normal")||"";var l=d.getAttribute("hotspot-name")||String(c),k=d.getAttribute("hotspot-title")||"",D=d.getAttribute("hotspot-description")||"";d=xa({K:a,hotspotName:l,position:e,normal:h,title:k,description:D,I:d.hasAttribute("info-card-hidden")});a.appendChild(d);c++}}}};function qa(a){return a.classList&&a.classList.contains("hotspot")?!0:!1}
f.getSceneGraphModel=function(){return X(this).model};f.getCameraDetails=function(){var a=X(this).getCameraOrbit(),b=a.theta,c=a.phi;a=a.radius;var d=X(this).getCameraTarget();return{yaw:b*S,pitch:c*S,zoom:a,x:d.x,y:d.y,z:d.z}};ca.Object.defineProperties(T,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return na}}});customElements.define("gwd-3d-model-viewer",T);}).call(this);
