(function(){'use strict';var n;function p(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var q=p(this),t="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},v;
if("function"==typeof Object.setPrototypeOf)v=Object.setPrototypeOf;else{var w;a:{var x={a:!0},y={};try{y.__proto__=x;w=y.a;break a}catch(a){}w=!1}v=w?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var z=v;
function A(a,b){a.prototype=t(b.prototype);a.prototype.constructor=a;if(z)z(a,b);else for(var d in b)if("prototype"!=d)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d];a.O=b.prototype};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var C=this||self;function D(a){a=1-a;return 1-a*a*a};var E=/[^\d]+$/;function F(a,b,d,f){if(!a.hasAttribute(b))return d;a=a.getAttribute(b);isNaN(parseFloat(a))?f=d:(d=parseFloat(a),(a=(a=a.match(E))&&a[0]||null)&&(a=a.trim()),b=d,"%"==a&&(b=Number((d/100*f).toFixed(2))),f=b);return f};function G(a,b,d){var f=F(a,"xenter",0,b),e=a.hasAttribute("xmiddle")?F(a,"xmiddle",0,b):void 0,c=F(a,"xexit",0,b),h=F(a,"yenter",0,d),m=a.hasAttribute("ymiddle")?F(a,"ymiddle",0,d):void 0,g=F(a,"yexit",0,d),k=H(a,"opacityenter"),l=H(a,"opacitymiddle"),r=H(a,"opacityexit"),B=a.hasAttribute("fixed"),S=a.getAttribute("assettype")||"",T=a.getAttribute("source")||"",U=a.getAttribute("easing")||"linear";b=F(a,"width",b,b);d=F(a,"height",d,d);var V=a.hasAttribute("yawenter")?parseInt(a.getAttribute("yawenter"),
10):void 0,W=a.hasAttribute("yawmiddle")?parseInt(a.getAttribute("yawmiddle"),10):void 0,X=a.hasAttribute("yawexit")?parseInt(a.getAttribute("yawexit"),10):void 0,Y=a.getAttribute("exit-url")||void 0,u=[];u.push({opacity:k,x:f,y:h,m:V});void 0!==e&&void 0!==m&&u.push({opacity:l,x:e,y:m,m:W});u.push({opacity:r,x:c,y:g,m:X});return{J:S,i:u,easing:U,element:a,F:Y,fixed:B,height:d,source:T,width:b}}
function I(a,b,d,f,e,c){e=void 0===e?0:e;c=void 0===c?1:c;if(f<=e)return a;if(f>=c)return b;switch(d){case "ease-in":d=f*f*f;e*=e*e;c*=c*c;break;case "ease-in-out":d=3*f*f-2*f*f*f;e=3*e*e-2*e*e*e;c=3*c*c-2*c*c*c;break;case "ease-out":d=D(f);e=D(e);c=D(c);break;default:d=f}return 1/(c-e)*(b-a)*(d-e)+a}function H(a,b){if(!a.hasAttribute(b))return 1;a=a.getAttribute(b);a=parseFloat(a);return isNaN(a)?1:0>a?0:1<a?1:a};function J(a,b,d){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=d);return a};function K(a){this.h=a}K.prototype.toString=function(){return this.h.toString()};K.prototype.l=!0;K.prototype.j=function(){return this.h.toString()};var L;try{new URL("s://g"),L=!0}catch(a){L=!1}var M=L,aa={};function N(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function ba(a){if(N(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&N(a))return a;return null};function O(a,b,d){d=void 0===d?null:d;var f=document.createEvent("CustomEvent");f.initCustomEvent(a,!0,!0,d);b.dispatchEvent(f);return f};var ca=[];function P(){var a=HTMLElement.call(this)||this;a.u=[];a.B=null;a.l=null;a.j=[0,1];a.h=[];a.v=a.K.bind(a);a.G=!1;a.C=!1;a.D=a.N.bind(a);a.A=0;a.I=a.M.bind(a);a.H=a.L.bind(a);a.o=null;return a}A(P,HTMLElement);n=P.prototype;
n.connectedCallback=function(){this.ownerDocument.addEventListener("hostpagescroll",this.D);window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.I),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.H));if(!this.gwdIsLoaded()){var a=ba(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};
n.disconnectedCallback=function(){this.ownerDocument.removeEventListener("hostpagescroll",this.D);window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.I),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.H));this.removeEventListener("ready",this.v,!1)};
n.gwdLoad=function(){if(!this.gwdIsLoaded()){this.h.length=0;this.initializeParallax(!0);for(var a=this.h.length-1;0<=a;a--)this.h[a].gwdLoad();this.h=this.h.filter(function(b){return!b.gwdIsLoaded()});0==this.h.length?Q(this):this.addEventListener("ready",this.v,!1)}};n.gwdIsLoaded=function(){return this.G&&0==this.h.length};n.K=function(a){a=this.h.indexOf(a.target);0<=a&&(this.h.splice(a,1),0==this.h.length&&(Q(this),this.removeEventListener("ready",this.v,!1)))};
function Q(a){a.C||O("ready",a);a.C=!0;a.o&&(R(a,a.o.creativeFramePercentY,a.o.windowHeight+a.l),a.o=null)}
n.initializeParallax=function(a){var b=this;this.style.overflow="hidden";this.u.length=0;this.B=this.clientWidth;this.l=this.clientHeight;this.j=da(this);for(var d=this.ownerDocument,f={},e=0;e<this.children.length;f={s:f.s},e++)if(!this.children[e].hasAttribute("data-gwd-csd-ghost-id")){var c=G(this.children[e],this.B,this.l);this.u.push(c);c.element.style.position="absolute";c.element.style.left="0px";c.element.style.top="0px";c.element.style.width=c.width+"px";c.element.style.height=c.height+"px";
c.element.style.transform="translate("+c.i[0].x+"px, "+c.i[0].y+"px)";c.element.style.opacity=c.i[0].opacity+"";void 0!=c.i[0].m&&c.element.setTargetYaw(c.i[0].m);if(a){if("image"==c.J&&c.source){for(;c.element.firstChild;)c.element.removeChild(c.element.firstChild);var h=d.createElement("gwd-image");h.style.width="100%";h.style.height="100%";h.setAttribute("source",c.source);this.h.push(h);c.element.appendChild(h)}else c.element.gwdLoad&&this.h.push(c.element);c.F&&(f.s=c.F,c.element.addEventListener("click",
function(m){return function(){if(!O("layerclickexit",b,{url:m.s}).detail.handled){var g=m.s;if(!(g instanceof K||g instanceof K)){g="object"==typeof g&&g.l?g.j():String(g);b:{var k=g;if(M){try{var l=new URL(k)}catch(r){k="https:";break b}k=l.protocol}else c:{l=document.createElement("a");try{l.href=k}catch(r){k=void 0;break c}k=l.protocol;k=":"===k||""===k?"https:":k}}"javascript:"===k&&(g="about:invalid#zClosurez");g=new K(g,aa)}C.open(g instanceof K&&g.constructor===K?g.h:"type_error:SafeUrl","")}}}(f)))}}this.G=
!0};n.N=function(a){a=a.detail;this.A=a.creativeFramePercentY;this.gwdIsLoaded()?R(this,a.creativeFramePercentY,a.windowHeight+this.l):this.o=a};
function R(a,b,d){for(var f=0;f<a.u.length;f++){var e=a.u[f],c=void 0,h=void 0;c=e.i.length-1;var m=a.j[0],g=a.j[a.j.length-1],k=e.i[0],l=e.i[e.i.length-1];if(e.i.length===a.j.length)for(h=0;h<c;h++)if(a.j[h]<=b&&b<=a.j[h+1]){m=a.j[h];g=a.j[h+1];k=e.i[h];l=e.i[h+1];break}e.fixed?(c=e.i[0].x,h=e.i[0].y+b*d):(c=I(k.x,l.x,e.easing,b,m,g),h=I(k.y,l.y,e.easing,b,m,g));var r=I(k.opacity,l.opacity,e.easing,b,m,g);e.element.style.transform="translate("+c+"px, "+h+"px)";e.element.style.opacity=r+"";e.i.some(function(B){return void 0===
B.m})||e.element.setTargetYaw(Math.round(I(k.m,l.m,e.easing,b,m,g)))}O("parallaxscrolled",a,{yscroll:b})}function da(a){var b=J(a,"start",0),d=J(a,"end",1);if(0>b||1<b||0>d||1<d||b>=d)b=0,d=1;a=J(a,"middle",-1);return a>=b&&a<=d?[b,a,d]:[b,d]}n.M=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);R(a,1,window.innerHeight+a.l)},1)};n.L=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);R(a,a.A,window.innerHeight+a.l)},1)};
q.Object.defineProperties(P,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ca}}});function Z(){return P.call(this)||this}A(Z,P);customElements.define("gwd-swirl",Z);}).call(this);
